baseurl: /garden

title: "呆恋小喵"
description: "分享个人学习经验及生活得失"
keywords: "前端开发"

author:
    name: "呆恋小喵"
    job: "前端开发工程师"
    bio: "本人女，前端打酱油一枚。2015年毕业于中国传媒大学数字媒体技术专业。爱好：逛街、淘宝、学习；专长：数学、绘画、卖萌。"
    email: "sunmy_meow@sina.com"
    github: "https://github.com/sunmengyuan"